/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.appreactor.frecuenciapalabras.aplicacion;

import co.appreactor.frecuenciapalabras.negocio.constantes.EOrigen;
import co.appreactor.frecuenciapalabras.negocio.servicio.ArbolServicio;
import co.appreactor.frecuenciapalabras.negocio.util.ConsolaUtil;
import java.awt.HeadlessException;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.text.BadLocationException;

/**
 *
 * @author lord_nightmare
 */
public class Principal extends javax.swing.JFrame {

  private File archivo;
  private ArbolServicio servicio;

  /**
   * Creates new form Principal
   */
  public Principal() {
    initComponents();
    init();
  }

  public final void init() {
    setTitle("Analizador de textos");
    this.setLocationRelativeTo(null);
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jScrollPane1 = new javax.swing.JScrollPane();
    txtConsola = new javax.swing.JTextPane();
    btnAbrir = new javax.swing.JButton();
    btnProcesar = new javax.swing.JButton();
    btnImprimir = new javax.swing.JButton();
    btnLimpiar = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    txtConsola.setEditable(false);
    jScrollPane1.setViewportView(txtConsola);

    btnAbrir.setText("Abrir Archivo");
    btnAbrir.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnAbrirActionPerformed(evt);
      }
    });

    btnProcesar.setText("Procesar Texto");
    btnProcesar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnProcesarActionPerformed(evt);
      }
    });

    btnImprimir.setText("Imprimir Arbol");
    btnImprimir.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnImprimirActionPerformed(evt);
      }
    });

    btnLimpiar.setText("Limpiar Consola");
    btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnLimpiarActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 730, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(btnAbrir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(btnProcesar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(btnImprimir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(btnLimpiar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        .addContainerGap())
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addComponent(btnAbrir)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(btnProcesar)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(btnImprimir)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(btnLimpiar)
            .addGap(0, 90, Short.MAX_VALUE))
          .addComponent(jScrollPane1))
        .addContainerGap())
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void btnAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbrirActionPerformed
    try {
      JFileChooser buscador = new JFileChooser();
      buscador.setFileFilter(new FileNameExtensionFilter("Archivo de texto", "txt"));
      int seleccion = buscador.showOpenDialog(rootPane);
      switch (seleccion) {
        case JFileChooser.APPROVE_OPTION:
          archivo = buscador.getSelectedFile();
          String mensaje = "El archivo con ruta: '"
            + archivo.getAbsolutePath()
            + "' ha sido cargado";
          ConsolaUtil.cargarMensaje(
            txtConsola.getStyledDocument(),
            EOrigen.ARCHIVO,
            mensaje
          );
          break;
        default:
          JOptionPane.showMessageDialog(
            rootPane,
            "Tarea Cancelada", "Seleccionar Archivo de texto",
            JOptionPane.CANCEL_OPTION
          );
      }
    } catch (HeadlessException | BadLocationException e) {
      e.printStackTrace(System.err);
    }
  }//GEN-LAST:event_btnAbrirActionPerformed

  private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
    txtConsola.setText("");
  }//GEN-LAST:event_btnLimpiarActionPerformed

  private void btnProcesarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProcesarActionPerformed
    try {
      this.servicio = new ArbolServicio(txtConsola, archivo);
      this.servicio.procesarTexto();
    } catch (IOException | BadLocationException e) {
      e.printStackTrace(System.err);
    }
  }//GEN-LAST:event_btnProcesarActionPerformed

  private void btnImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirActionPerformed
    if (this.servicio == null) {
      JOptionPane.showMessageDialog(
        rootPane,
        "Tarea Cancelada", "Seleccionar Archivo de texto",
        JOptionPane.CANCEL_OPTION
      );
      return;
    }
    try {
      servicio.getArbolPalabras().imprimirInOrden();
    } catch (BadLocationException e) {
      e.printStackTrace(System.err);
    }
  }//GEN-LAST:event_btnImprimirActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
 /*try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }*/
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(() -> {
      new Principal().setVisible(true);
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btnAbrir;
  private javax.swing.JButton btnImprimir;
  private javax.swing.JButton btnLimpiar;
  private javax.swing.JButton btnProcesar;
  private javax.swing.JScrollPane jScrollPane1;
  public static javax.swing.JTextPane txtConsola;
  // End of variables declaration//GEN-END:variables
}
