/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.appreactor.tiendahash.negocio;

import co.appreactor.tiendahash.persistencia.GestorProductos;
import java.awt.Frame;
import javax.swing.JOptionPane;

/**
 *
 * @author lord_nightmare
 */
public class Crear extends javax.swing.JDialog {

  private final GestorProductos gestor;
  private final Principal principal;

  /**
   * Creates new form Crear
   *
   * @param principal
   * @param gestor
   * @param owner
   * @param modal
   */
  public Crear(Principal principal, GestorProductos gestor, Frame owner, boolean modal) {
    super(owner, modal);
    this.principal = principal;
    this.gestor = gestor;
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jLabel1 = new javax.swing.JLabel();
    txtCodigoCrear = new javax.swing.JTextField();
    jLabel2 = new javax.swing.JLabel();
    txtPrecioCrear = new javax.swing.JTextField();
    btnRegistrar = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    setTitle("Crear producto");

    jLabel1.setText("Codigo");

    jLabel2.setText("Precio");

    btnRegistrar.setText("Registrar Producto");
    btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnRegistrarActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
          .addComponent(btnRegistrar)
          .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
            .addComponent(jLabel1)
            .addComponent(jLabel2)
            .addComponent(txtCodigoCrear)
            .addComponent(txtPrecioCrear, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jLabel1)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(txtCodigoCrear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jLabel2)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(txtPrecioCrear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(btnRegistrar)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    pack();
    setLocationRelativeTo(null);
  }// </editor-fold>//GEN-END:initComponents

  private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
    try {
      String codigo = txtCodigoCrear.getText();
      Double precio = Double.parseDouble(txtPrecioCrear.getText());
      gestor.guardarProducto(codigo, precio);
      principal.actualizarTabla();
      this.setVisible(false);
      this.limpiarFormulario();
    } catch (NumberFormatException e) {
      JOptionPane.showMessageDialog(
        null, "El precio del producto debe ser una cantidad numerica",
        "Registro de producto",
        JOptionPane.ERROR_MESSAGE
      );
    }
  }//GEN-LAST:event_btnRegistrarActionPerformed

  private void limpiarFormulario(){
    txtCodigoCrear.setText("");
    txtPrecioCrear.setText("");
  }
  
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btnRegistrar;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JTextField txtCodigoCrear;
  private javax.swing.JTextField txtPrecioCrear;
  // End of variables declaration//GEN-END:variables
}
