/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.appreactor.tiendahash.negocio;

import co.appreactor.tiendahash.persistencia.GestorProductos;
import javax.swing.JOptionPane;

/**
 *
 * @author lord_nightmare
 */
public class Modificar extends javax.swing.JDialog {

  private final GestorProductos gestor;
  private final String codigo;
  private final Principal principal;

  /**
   * Creates new form Modificar
   *
   * @param parent
   * @param gestor
   * @param codigo
   * @param modal
   */
  public Modificar(java.awt.Frame parent, GestorProductos gestor, String codigo, Principal principal, boolean modal) {
    super(parent, modal);
    initComponents();
    this.codigo = codigo;
    this.gestor = gestor;
    txtNuevoPrecio.setText(this.gestor.buscarProducto(this.codigo) + "");
    this.principal = principal;
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jLabel1 = new javax.swing.JLabel();
    txtNuevoPrecio = new javax.swing.JTextField();
    btnModificar = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    setTitle("Modificar producto");

    jLabel1.setText("Nuevo precio");

    btnModificar.setText("Guardar");
    btnModificar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnModificarActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jLabel1)
          .addComponent(txtNuevoPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addComponent(btnModificar)
        .addContainerGap())
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jLabel1)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(txtNuevoPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addComponent(btnModificar)
        .addContainerGap())
    );

    pack();
    setLocationRelativeTo(null);
  }// </editor-fold>//GEN-END:initComponents

  private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
    try {
      Double precio = Double.parseDouble(txtNuevoPrecio.getText());
      gestor.modificarProducto(codigo, precio);
      principal.actualizarTabla();
      this.setVisible(false);
      this.txtNuevoPrecio.setText("");
    } catch (NumberFormatException e) {
      JOptionPane.showMessageDialog(
        null, "El precio del producto debe ser una cantidad numerica",
        "Registro de producto",
        JOptionPane.ERROR_MESSAGE
      );
    }
  }//GEN-LAST:event_btnModificarActionPerformed

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btnModificar;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JTextField txtNuevoPrecio;
  // End of variables declaration//GEN-END:variables
}
